"""Build the three notebooks programmatically."""
import nbformat as nbf
from pathlib import Path

ROOT = Path(__file__).resolve().parent
NB_DIR = ROOT / "notebooks"
NB_DIR.mkdir(exist_ok=True)


def notebook(title, cells):
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    nb.metadata["kernelspec"] = {
        "name": "python3", "display_name": "Python 3", "language": "python"
    }
    nb.metadata["language_info"] = {"name": "python"}
    return nb


def md(s): return nbf.v4.new_markdown_cell(s)
def code(s): return nbf.v4.new_code_cell(s)


# ------------------------------------------------------------------
# 01_eda.ipynb
# ------------------------------------------------------------------
eda_cells = [
    md("""# 01 — Exploratory Data Analysis

Quick tour of the 1994/95 CPS "census-bureau" dataset. This notebook reproduces
and extends what `src/eda.py` does, with interactive outputs inline.

**Goal of the project**
1. Train a classifier to predict whether a person earns more than \\$50k/yr
   so the retail client can size and target income-tier marketing campaigns.
2. Build a population segmentation so the client can tailor creative, offers
   and channels to meaningful life-stage / economic groups.
"""),
    code("""import sys, json
from pathlib import Path
import numpy as np, pandas as pd, matplotlib.pyplot as plt

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT / "src"))
from data_utils import (load_raw, drop_exact_duplicates,
                        LABEL_COL, WEIGHT_COL, NUMERIC_COLS, CATEGORICAL_COLS)

df = drop_exact_duplicates(load_raw(ROOT / "data" / "census-bureau.data"))
print("Shape:", df.shape)
df.head()"""),
    md("""## Class balance

Important: the data comes from a stratified sample, so rows carry a
**weight** that tells us the relative frequency in the true population.
We always report class balance and evaluation metrics *both* weighted and
unweighted."""),
    code("""unw = df[LABEL_COL].mean()
w   = (df[LABEL_COL] * df[WEIGHT_COL]).sum() / df[WEIGHT_COL].sum()
print(f"Unweighted positive rate: {unw:.4f}")
print(f"Weighted positive rate  : {w:.4f}")
df[LABEL_COL].map({0:'<=50K', 1:'>50K'}).value_counts()"""),
    md("## Missingness\n\nThe `?` sentinel was converted to NaN in `load_raw`. A handful of columns are ~50% missing."),
    code("""miss = df.isna().mean().sort_values(ascending=False)
miss[miss > 0].head(10)"""),
    md("## Figures generated by `src/eda.py`"),
    code("""from IPython.display import Image
for p in sorted((ROOT / "figures").glob("0[1-5]*.png")):
    display(Image(filename=str(p)))"""),
    md("""## Key observations

* **Severe class imbalance** (~6% positive) — accuracy is the wrong metric; we
  will use ROC-AUC, PR-AUC, and F1 at a tuned threshold.
* **`weight` is a sampling weight, not a feature** — drop it from X, pass it
  as `sample_weight` to models and metrics.
* **Duplicates**: ~3,200 rows are exact duplicates; we de-duplicate before
  splitting to avoid leakage.
* **`Not in universe`** is a valid "this question doesn't apply" code, not a
  data-quality issue. We keep it as a level.
* **Four migration columns are ~50% missing** because they are only collected
  for people who moved. We impute with `missing` and let the tree model use
  missingness as signal.
"""),
]

# ------------------------------------------------------------------
# 02_classifier.ipynb
# ------------------------------------------------------------------
cls_cells = [
    md("""# 02 — Income Classifier

This notebook summarises the classifier training that `src/train_classifier.py`
runs end-to-end. Re-running `python src/train_classifier.py` from the project
root regenerates every artefact referenced here."""),
    code("""import json, sys
from pathlib import Path
import pandas as pd
from IPython.display import Image

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
metrics = json.loads((ROOT / "outputs" / "classifier_metrics.json").read_text())
metrics"""),
    md("""## Model line-up

| Model | Use |
| --- | --- |
| **Logistic Regression** (balanced) | Interpretable baseline |
| **LightGBM** (scale_pos_weight, early stopping on val PR/AUC) | Main model |

Both use the same preprocessing pipeline:

* median imputation for numerics (tree model doesn't care; we keep it uniform for
  the pipeline),
* one-hot encoding with `min_frequency=50` to collapse rare category levels,
* sample weights are passed through to training *and* metric computation."""),
    code("""pd.DataFrame({
    "Logistic": metrics["logreg"]["test"],
    "LightGBM": metrics["lightgbm"]["test"],
})"""),
    md("## Curves & confusion matrix (test set, weighted)"),
    code("""for p in sorted((ROOT / "figures").glob("0[6-8]*.png")):
    display(Image(filename=str(p)))"""),
    md("""## Top drivers of income"""),
    code("""imp = pd.read_csv(ROOT / "outputs" / "feature_importance.csv")
imp.head(15)"""),
    md("""## Business interpretation

* **Weeks worked, age, and dividend income dominate** — people with full-year
  employment and investment income are far more likely to cross the \\$50k line.
* **Non-filer tax status** is a strong negative signal (often retirees, kids,
  or very low income).
* **Occupation/education** add incremental signal but are dwarfed by capital
  and employment intensity.
* **Recommended decision threshold ≈ 0.29**. At this threshold, the model
  trades a little precision for big recall gains — appropriate for a marketing
  funnel that can tolerate false positives more than false negatives.
"""),
]

# ------------------------------------------------------------------
# 03_segmentation.ipynb
# ------------------------------------------------------------------
seg_cells = [
    md("""# 03 — Marketing Segmentation

Unsupervised segmentation built with `src/segment.py`. We cluster the population
using a marketing-actionable feature subset (life stage, employment intensity,
capital behaviour) and profile the resulting groups.

**Why not just split by the classifier's predicted income?**  The client asked
for segmentation for *marketing*, which is about offer/creative fit, not just
income. People with similar incomes can have very different life stages
(retiree vs young professional) and therefore very different marketing needs.
"""),
    code("""import json, sys
from pathlib import Path
import pandas as pd
from IPython.display import Image

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
summary = json.loads((ROOT / "outputs" / "segmentation_summary.json").read_text())
print(f"Best k by silhouette: {summary['best_k']}")
print(f"PCA cumulative variance (10 PCs): {summary['pca_cumulative_variance']:.3f}")"""),
    md("## K selection"),
    code("""Image(filename=str(ROOT / 'figures' / '09_elbow_silhouette.png'))"""),
    md("## Segments in PCA space"),
    code("""Image(filename=str(ROOT / 'figures' / '10_segments_scatter.png'))"""),
    md("## Segment profiles"),
    code("""pd.read_csv(ROOT / 'outputs' / 'segment_profiles.csv')"""),
    md("## Size & income propensity"),
    code("""Image(filename=str(ROOT / 'figures' / '11_segment_profiles.png'))"""),
    md("""## Marketing read (see report for the full version)

* **High-earner segments** (weighted P(>\\$50k) above ~25%): small population shares
  (~2–16%) but carry the purchase power — target with premium, financial, and
  aspirational creative.
* **Dual-income household spouses** and **young single urban workers** sit around
  the population mean — these are the volume play; run broad-reach campaigns
  here.
* **Retirees** (low positive rate, investment income, older): good candidates
  for health, travel, and value-oriented messaging.
* **Children** (two segments split by sex): not a direct marketing target for
  the retailer, but valuable as a household indicator if joining to parent
  records.
"""),
]

for name, cells in [("01_eda.ipynb", eda_cells),
                    ("02_classifier.ipynb", cls_cells),
                    ("03_segmentation.ipynb", seg_cells)]:
    nb = notebook(name, cells)
    path = NB_DIR / name
    nbf.write(nb, path)
    print(f"Wrote {path}")
